# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Lisa Levoir" # Your name
  description: "Lisa Levoir is an applied statistician" # A brief slogan (optional)
  image: img/me.png

  favicon: img/favicon.png

  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: img/logo.png

    # your sub-pages
    left:
      - text: "Projects"
        href: projects/index.qmd
      #- text: "Photography"
      # href: photography/index.qmd
      - text: "CV"
        href: cv/index.qmd

    # your social media handles
    right:
      - icon: github
        href: https://github.com/LisaLevoir
      - icon: linkedin
        href: https://www.linkedin.com/in/llevoir/
      - icon: envelope
        aria-label: email
        href: "mailto:lisa.m.levoir@vanderbilt.edu"

  # Don't touch unless you know what you are doing :) ------------
  search:
    location: navbar
    type: textbox
  page-footer:
    left: |
      <span class="faux-block">&#169; 2025 Lisa Levoir CC BY-SA 4.0</span>
    #center: |
    # <span class="faux-block"><a href="https://www.linkedin.com/in/llevoir/">Reach out on LinkedIn</a></span>
    right: |
      <span class="faux-block"><a href="https://icons8.com/icon/4IZ8RiC9K8go/star">Star</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a></span>

project:
  type: website
  output-dir: docs

  preview:
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme:
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
