project:
  type: website
  output-dir: docs

website:
  title: "Lisa Levoir"
  description: "This is Lisa Levoir's website."
  navbar:
    right:
      - text: About Me
        href: about.qmd
      - text: CV
        href: cvpage.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/llevoir/
      - icon: github
        href: https://github.com/LisaLevoir

format:
  html:
    theme: flatly
    css: styles.css

editor: visual

